# Generated by Django 5.0.2 on 2024-02-12 06:42

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.FileField(upload_to='hotel_gallery')),
                ('address', models.CharField(max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(choices=[('Live', 'Live'), ('Disabled', 'Disabled'), ('in repair', 'in repair')], default='Live', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('tags', models.CharField(blank=True, max_length=100, null=True)),
                ('views', models.IntegerField(default=0)),
                ('hotel_id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz123', length=6, max_length=20, prefix='', unique=True)),
                ('slug', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
