# Generated by Django 5.0.2 on 2024-02-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_booking_coupons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='success_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
