# Generated by Django 5.0.2 on 2024-03-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_alter_booking_success_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('NOT PAID', 'NOT PAID'), ('PAID', ' PAID'), ('PENDING', 'PENDING'), ('processing', 'processing'), ('failed', 'failed'), ('refunded', 'refunded'), ('CANCELLED', 'CANCELLED')], default='NOT PAID', max_length=100),
        ),
    ]
