# Generated by Django 5.0.2 on 2024-03-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.FileField(upload_to='menu_images')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('category', models.ManyToManyField(related_name='item', to='user_dashboard.category')),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('room_type', models.CharField(blank=True, max_length=100, null=True)),
                ('room_number', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.IntegerField(blank=True, null=True)),
                ('payment_status', models.CharField(blank=True, choices=[('NOT PAID', 'NOT PAID'), ('PAID', ' PAID'), ('PENDING', 'PENDING'), ('processing', 'processing'), ('failed', 'failed'), ('refunded', 'refunded'), ('CANCELLED', 'CANCELLED')], default='NOT PAID', max_length=100, null=True)),
                ('items', models.ManyToManyField(blank=True, related_name='order', to='user_dashboard.menuitem')),
            ],
        ),
    ]
