# Generated by Django 5.0.2 on 2024-02-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=50)),
                ('state', models.CharField(blank=True, max_length=30)),
                ('otp', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
