# Generated by Django 5.0.2 on 2024-03-12 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_alter_booking_username'),
        ('userauth', '0002_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
